<?php
/**
 * Soft integrity assist — heuristics + manual flags. Never auto-rejects.
 *
 * @package WisdomJournalManager
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WJM_Integrity {

	const META      = '_sjm_integrity_flags';
	const META_AUTO = '_sjm_integrity_auto';
	const META_NOTE = '_sjm_integrity_note';

	public static function init() {
		add_action( 'add_meta_boxes', array( __CLASS__, 'meta_box' ) );
		add_action( 'save_post_sjm_paper', array( __CLASS__, 'save' ), 26, 2 );
		add_action( 'sjm_workflow_transition', array( __CLASS__, 'on_transition' ), 15, 4 );
		add_action( 'sjm_after_save_paper', array( __CLASS__, 'scan_and_store' ) );
	}

	/**
	 * @return array key => label
	 */
	public static function flag_defs() {
		return array(
			'ai_disclosure'     => __( 'AI use disclosed / needs check', 'wisdom-journal-manager' ),
			'image_concern'     => __( 'Figure / image integrity concern', 'wisdom-journal-manager' ),
			'data_anomaly'      => __( 'Data / stats anomaly flag', 'wisdom-journal-manager' ),
			'authorship_issue'  => __( 'Authorship / contributorship dispute', 'wisdom-journal-manager' ),
			'plagiarism_review' => __( 'Similarity needs human review', 'wisdom-journal-manager' ),
			'ethics_followup'   => __( 'Ethics / consent follow-up', 'wisdom-journal-manager' ),
			'missing_orcid'     => __( 'Author ORCID missing', 'wisdom-journal-manager' ),
			'duplicate_title'   => __( 'Similar title already in system', 'wisdom-journal-manager' ),
		);
	}

	/**
	 * @param int $paper_id Paper ID.
	 * @return array
	 */
	public static function get_flags( $paper_id ) {
		$flags = get_post_meta( $paper_id, self::META, true );
		return is_array( $flags ) ? $flags : array();
	}

	/**
	 * @param int $paper_id Paper ID.
	 * @return array key => reason string
	 */
	public static function get_auto( $paper_id ) {
		$auto = get_post_meta( $paper_id, self::META_AUTO, true );
		return is_array( $auto ) ? $auto : array();
	}

	/**
	 * @param int $paper_id Paper ID.
	 * @return bool
	 */
	public static function has_any( $paper_id ) {
		foreach ( self::get_flags( $paper_id ) as $v ) {
			if ( ! empty( $v ) ) {
				return true;
			}
		}
		return (bool) self::get_auto( $paper_id );
	}

	/**
	 * Heuristic scan — soft only.
	 *
	 * @param int $paper_id Paper ID.
	 * @return array key => reason
	 */
	public static function scan( $paper_id ) {
		$paper_id = absint( $paper_id );
		$hits     = array();
		$title    = get_the_title( $paper_id );
		$abstract = (string) get_post_meta( $paper_id, '_sjm_abstract', true );
		$blob     = strtolower( $title . ' ' . $abstract );
		$sim      = get_post_meta( $paper_id, '_sjm_similarity_pct', true );
		$thresh = 25;
		if ( class_exists( 'WJM_Ithenticate' ) && method_exists( 'WJM_Ithenticate', 'settings' ) ) {
			$s = WJM_Ithenticate::settings();
			if ( isset( $s['warn_threshold'] ) && '' !== $s['warn_threshold'] ) {
				$thresh = (float) $s['warn_threshold'];
			}
		}

		if ( '' !== $sim && null !== $sim && is_numeric( $sim ) && (float) $sim >= $thresh ) {
			$hits['plagiarism_review'] = sprintf(
				/* translators: 1: percent 2: threshold */
				__( 'Similarity %1$s%% ≥ %2$s%% — review before decide.', 'wisdom-journal-manager' ),
				$sim,
				$thresh
			);
		}

		if ( strlen( trim( wp_strip_all_tags( $abstract ) ) ) < 80 ) {
			$hits['data_anomaly'] = __( 'Abstract missing or very short (< 80 chars).', 'wisdom-journal-manager' );
		}

		if ( preg_match( '/\b(chatgpt|gpt-4|gpt4|claude\.ai|generated by (an )?ai|llm-generated)\b/i', $blob )
			&& ! preg_match( '/\b(ai disclosure|disclos(e|ed) (use of )?ai|we used (chatgpt|an llm))\b/i', $blob ) ) {
			$hits['ai_disclosure'] = __( 'AI tooling mentioned without clear disclosure language.', 'wisdom-journal-manager' );
		}

		$ethics = (string) get_post_meta( $paper_id, '_sjm_ethics', true );
		$access = class_exists( 'WJM_Access' ) ? WJM_Access::settings() : array();
		if ( ! empty( $access['require_ethics'] ) && '' === trim( $ethics ) ) {
			$hits['ethics_followup'] = __( 'Ethics statement required by Access but empty.', 'wisdom-journal-manager' );
		}

		$emails  = array();
		$authors = class_exists( 'WJM_Author_Profiles' ) ? WJM_Author_Profiles::get_authors_for_paper( $paper_id ) : array();
		if ( $authors ) {
			$orcid_missing = true;
			foreach ( $authors as $a ) {
				if ( ! empty( $a->orcid ) ) {
					$orcid_missing = false;
				}
				if ( ! empty( $a->email ) ) {
					$emails[] = strtolower( $a->email );
				}
			}
			if ( $orcid_missing ) {
				$hits['missing_orcid'] = __( 'No ORCID on linked authors.', 'wisdom-journal-manager' );
			}
			if ( count( $emails ) !== count( array_unique( $emails ) ) ) {
				$hits['authorship_issue'] = __( 'Duplicate author emails on this paper.', 'wisdom-journal-manager' );
			}
		}

		// Near-duplicate title among other papers.
		if ( strlen( $title ) > 12 ) {
			$others = get_posts(
				array(
					'post_type'      => 'sjm_paper',
					'post_status'    => array( 'publish', 'private', 'draft', 'pending' ),
					'posts_per_page' => 30,
					's'              => $title,
					'post__not_in'   => array( $paper_id ),
					'fields'         => 'ids',
				)
			);
			foreach ( $others as $oid ) {
				$ot = get_the_title( $oid );
				similar_text( strtolower( $title ), strtolower( $ot ), $pct );
				if ( $pct >= 88 ) {
					$hits['duplicate_title'] = sprintf(
						/* translators: %s: other paper title */
						__( 'Very similar title to: %s', 'wisdom-journal-manager' ),
						$ot
					);
					break;
				}
			}
		}

		return $hits;
	}

	/**
	 * @param int $paper_id Paper ID.
	 */
	public static function scan_and_store( $paper_id ) {
		$hits = self::scan( $paper_id );
		update_post_meta( $paper_id, self::META_AUTO, $hits );

		// Merge plagiarism auto into manual soft flag for inbox visibility.
		$flags = self::get_flags( $paper_id );
		if ( isset( $hits['plagiarism_review'] ) ) {
			$flags['plagiarism_review'] = 1;
			update_post_meta( $paper_id, self::META, $flags );
		}
	}

	public static function on_transition( $paper_id, $from, $to, $note ) {
		if ( in_array( $to, array( 'submitted', 'screening', 'under_review', 'resubmitted' ), true ) ) {
			self::scan_and_store( $paper_id );
		}
		unset( $from, $note );
	}

	public static function meta_box() {
		add_meta_box(
			'wjm_integrity',
			__( 'Integrity assist (soft)', 'wisdom-journal-manager' ),
			array( __CLASS__, 'render' ),
			'sjm_paper',
			'side',
			'high'
		);
	}

	public static function render( $post ) {
		self::scan_and_store( $post->ID );
		$flags = self::get_flags( $post->ID );
		$auto  = self::get_auto( $post->ID );
		$note  = get_post_meta( $post->ID, self::META_NOTE, true );
		$sim   = get_post_meta( $post->ID, '_sjm_similarity_pct', true );

		echo '<p class="description">' . esc_html__( 'Auto-scan + manual flags. Never auto-rejects — editors decide.', 'wisdom-journal-manager' ) . '</p>';

		if ( $auto ) {
			echo '<p><strong>' . esc_html__( 'Auto signals', 'wisdom-journal-manager' ) . '</strong></p><ul style="margin:0 0 0.75rem 1.1rem;">';
			foreach ( $auto as $reason ) {
				echo '<li>' . esc_html( $reason ) . '</li>';
			}
			echo '</ul>';
		} else {
			echo '<p class="description">' . esc_html__( 'Auto-scan: no signals.', 'wisdom-journal-manager' ) . '</p>';
		}

		if ( '' !== $sim && null !== $sim ) {
			echo '<p><strong>' . esc_html__( 'Similarity %:', 'wisdom-journal-manager' ) . '</strong> ' . esc_html( $sim );
			$src = get_post_meta( $post->ID, '_sjm_similarity_source', true );
			if ( $src ) {
				echo ' <span class="description">(' . esc_html( $src ) . ')</span>';
			}
			echo '</p>';
		}

		foreach ( self::flag_defs() as $key => $label ) {
			printf(
				'<p><label><input type="checkbox" name="sjm_integrity_flags[%s]" value="1" %s /> %s</label></p>',
				esc_attr( $key ),
				checked( ! empty( $flags[ $key ] ) || isset( $auto[ $key ] ), true, false ),
				esc_html( $label )
			);
		}
		echo '<p><label><strong>' . esc_html__( 'Notes', 'wisdom-journal-manager' ) . '</strong></label>';
		echo '<textarea class="widefat" rows="3" name="sjm_integrity_note">' . esc_textarea( $note ) . '</textarea></p>';
		echo '<p><button type="submit" class="button button-small" name="sjm_integrity_rescan" value="1">' . esc_html__( 'Re-run scan', 'wisdom-journal-manager' ) . '</button></p>';
	}

	public static function save( $post_id, $post ) {
		if ( wp_is_post_revision( $post_id ) || ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) ) {
			return;
		}
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}
		if ( ! isset( $_POST['sjm_integrity_note'] ) && ! isset( $_POST['sjm_integrity_flags'] ) && empty( $_POST['sjm_integrity_rescan'] ) ) {
			return;
		}
		$defs  = self::flag_defs();
		$raw   = isset( $_POST['sjm_integrity_flags'] ) ? (array) wp_unslash( $_POST['sjm_integrity_flags'] ) : array();
		$flags = array();
		foreach ( array_keys( $defs ) as $key ) {
			$flags[ $key ] = ! empty( $raw[ $key ] ) ? 1 : 0;
		}
		update_post_meta( $post_id, self::META, $flags );
		if ( isset( $_POST['sjm_integrity_note'] ) ) {
			update_post_meta( $post_id, self::META_NOTE, sanitize_textarea_field( wp_unslash( $_POST['sjm_integrity_note'] ) ) );
		}
		self::scan_and_store( $post_id );
		unset( $post );
	}
}
